baizhi_cat_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu_app/',include('menu_app.urls')),
    path('main_app/',include('main_app.urls')),
    path('echarts_app/',include('echarts_app.urls')),
    path('login_regist_app/', include('login_regist_app.urls'))

]

echarts_app/urls.py
from django.contrib import admin
from django.urls import path
from echarts_app import views
app_name='echarts_app'
urlpatterns = [
    path('map/',views.map,name='map' ),
    path('map_view/',views.map_view,name='map_view' ),
    path('bar/',views.bar,name='bar' ),
    path('barajax/',views.barajax,name='barajax' ),
    path('zhexian/',views.zhexian,name='zhexian'),
    path('zhexianajax/',views.zhexianajax,name='zhexianajax'),
    path('pie/',views.pie,name='pie' ),
    path('get_pie/',views.get_pie,name='get_pie' ),
    path('map/',views.map,name='map' ),
    path('map_view/',views.map_view,name='map_view' ),
]

login_regist_app/urls.py
from django.contrib import admin
from django.urls import path
from login_regist_app import views
app_name='login_regist_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('login_logic/', views.login_logic, name='login_logic'),
    path('login_ok/', views.login_ok, name='login_ok'),
    path('regist/',views.regist,name='regist'),
    path('registlogic/',views.registlogic,name='registlogic'),
    path('usernameajax/',views.usernameajax,name='usernameajax'),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path
from main_app import views

app_name='main_app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',views.main_show,name='main'),
    path('text/',views.text,name='text'),
    path('introduce_show/',views.introduce_show,name='introduce'),
    path('captcha_url/',views.captcha_url,name='captcha_url'),
    path('getcaptcha/',views.getcaptcha,name='getcaptcha'),
    path('check_captcha/',views.check_captcha,name='check_captcha'),

]

menu_app/urls.py
from django.contrib import admin
from django.urls import path
from menu_app import views
app_name='menu_app'

urlpatterns = [
    path('menu_view/',views.menu_view,name='menu_view'),
    path('menu_show_data/',views.menu_show_data,name='menu_show_data'),
    path('getcaptcha/',views.getcaptcha,name='getcaptcha'),
    # path('menu_show_error/',views.menu_show_error,name='menu_show_error'),

]

login_regist_app/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username=models.CharField(max_length=20)
    phone=models.CharField(max_length=20)
    email_addr=models.CharField(max_length=30)
    password=models.CharField(max_length=20)
    class Meta:
        db_table="user"

templates/captcha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>验证信息</title>
</head>
<style>
    body{
        background-color: yellow;
    }
    #box{
        width: 300px;
        height: 230px;
        margin: auto;
        margin-top: 30px;
        background-color: greenyellow;
    }
    #b1{
        width: 200px;
        height: 80px;
        margin: auto;
        padding-top: 20px;

    }
    #b2{
        text-align: center;
        line-height: 30px;
        font-size: 20px;
    }
    #b3{
        width: 200px;
        height: 30px;
        margin-left: 50px;
        margin-top: 5px;
        }
    #b4{
        width: 205px;
        height: 30px;
        margin-left: 50px;
        margin-top: 10px;
    }


</style>
<body>
    <div style="text-align: center;font-size: 50px;line-height: 200px">
        <span>请验证身份信息</span>
    </div>
    <div id="box">
        <form action="{% url 'main_app:check_captcha' %}" method="get">
            <div id="b1">
                <img src="{% url 'main_app:getcaptcha' %}" id="image_code" width="200px" height="70px" align="center">
            </div>
            <div id="b2">
                <a href="javascript:void(0)" onclick="change()">看不清，换一张</a>
            </div>
            <div >
                <input type="text" name="code_id" id="b3">
            </div>
            <div >
                <input type="submit" value="Submit" id="b4">
            </div>
        </form>
    </div>




</body>

<script>
    function change() {
        url=document.getElementById("image_code");
        url.src="{% url 'main_app:getcaptcha' %}?"+new Date().getTime();

    }
</script>
</html>

templates/crawler_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>访问太多！请休息一下</title>
</head>
<body>
    <div style="margin-top: 200px; margin-left: 500px">
        <h1>访问太多！请休息一下</h1>
    </div>
</body>
</html>

templates/introduce.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>百智招聘</title>
<link href="{% static 'style/authority/basic_layout.css'%}" rel="stylesheet" type="text/css">
<link href="{% static 'style/authority/common_style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
	<div id="container">
		<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center"  border="0">
		    <tr>
		      <th colspan="2">系统版本</th>
		    </tr>
		    <tr>
		      <td width="100" height="30">当前版本<span class="TableRow2"></span></td>
		      <td style="text-align:left">百智招聘系统 4.1</td>
		    </tr>
		</table>
	</div>
    <div id="main4" style="width: 500px;height: 500px;"></div>
    <div id="main1" style="width: 500px;height: 500px;"></div>
    <div id="main3" style="width: 500px;height: 500px;"></div>
    <div id="main2" style="width: 100%;height: 500px"></div>
    <script src="{% static 'jq/jquery1.4.2.js' %}"></script>
    <script>
        $('#main4').load('{% url "echarts_app:map_view" %}');
        $('#main1').load('{% url "echarts_app:bar" %}');
        $('#main2').load('{% url "echarts_app:zhexian" %}');
        $('#main3').load('{% url "echarts_app:get_pie" %}');

    </script>
</body>
</html>

templates/login.html
<!doctype html>
{% load static %}
<html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- font files  -->
<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>
<!-- /font files  -->
<!-- css files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css files -->
</head>
<body>
<h1>Login</h1>
<div class="log">
	<div class="content1">
		<h2>Login</h2>
		<form action="{% url 'login_regist_app:regist' %}" method="post">
            {% csrf_token %}
			<input type="text" id="name" name="userid" value="USERNAME" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'USERNAME';}">
			<input type="password" id="pwd" name="psw" value="PASSWORD" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'PASSWORD';}">
			<div class="button-row">
				<input type="button" class="sign-in" value="Sign In" onclick="check()"/>
				<input type="submit" class="reset" value="Reset">
				<div class="clear"></div>
			</div>
		</form>
	</div>

	<div class="clear"></div>
</div>
<div class="footer">
	<p>Copyright &copy;  <a href="http://www.baizhiedu.com/" target="_blank" title="百知教育">百知教育</a></p>
</div>

</body>

<script type="text/javascript">

    function check() {
        name=document.getElementById('name').value;
        pwd=document.getElementById('pwd').value;
        var xhr;
        if (window.XMLHttpRequest){
            xhr=new XMLHttpRequest()
        }else if(window.ActiveXObject){
            xhr=new ActiveXObject('Microsoft.XMLHTTP')
        }
        xhr.open("post","{% url 'login_regist_app:login_logic' %}",true);
        xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        xhr.send("name="+name+"&pwd="+pwd+"&csrfmiddlewaretoken="+"{{ csrf_token }}");
        xhr.onreadystatechange=function () {
            if (xhr.readyState==4 && xhr.status==200){
                if (xhr.responseText=='用户名或密码错误！'){
                    alert(xhr.responseText);
                }
                else if(xhr.responseText=='成功'){
                    location.href= "{% url 'login_regist_app:login_ok'%}?name="+name+'&pwd='+pwd;
                }
            }
        }

    }

</script>


</html>

templates/menu.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="/static/scripts/jquery/jquery-1.7.1.js"></script>
<link href="/static/style/authority/basic_layout.css" rel="stylesheet" type="text/css">
<link href="/static/style/authority/common_style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/static/scripts/authority/commonAll.js"></script>
<script type="text/javascript" src="/static/scripts/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="/static/scripts/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/static/style/authority/jquery.fancybox-1.3.4.css" media="screen"></link>
<script type="text/javascript" src="/static/scripts/artDialog/artDialog.js?skin=default"></script>
<title>百智招聘</title>
<script type="text/javascript">
</script>
<style>
</style>
</head>
<body>
	<form id="submitForm" name="submitForm" action="" method="post">
		<input type="hidden" name="allIDCheck" value="" id="allIDCheck"/>
		<input type="hidden" name="fangyuanEntity.fyXqName" value="" id="fyXqName"/>
		<div id="container">
			<div class="ui_content">
				<div class="ui_text_indent">
					<div id="box_border">
						<div id="box_top">搜索</div>
						<div id="box_center">
							<select name="fangyuanEntity.fyXqCode" id="fyXq" class="ui_select01" onchange="getFyDhListByFyXqCode();">
                                <option value="" id="a"
                                >--请选择--</option>
                                <option value="1">城市</option>
                                <option value="2">职位</option>
                            </select>
							<input type="text" id="fyZldz" name="fangyuanEntity.fyZldz" class="ui_input_txt02" />
							<input type="button" value="查询" class="ui_input_btn01" onclick="search();"/>
                            <script>
                                function search(){
                                    console.log(111);
                                    tiaojian1=document.getElementById('fyXq').value;
                                    tiaojian2=document.getElementById('fyZldz').value;
                                    location.href="{% url 'menu_app:menu_show_data' %}?flag="+tiaojian1+"&keyword="+tiaojian2+"&city_id=&position_id="}
                            </script>
						</div>
					</div>
				</div>
			</div>
			<div class="ui_content">
				<div class="ui_tb">
					<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center" border="0">
						<tr>
							
						
							<th>职位</th>
							<th>公司</th>
							<th>月薪</th>
							<th>任职要求</th>
							<th>经验要求</th>
							<th>学历要求</th>
							<th>公司地点</th>
							<th>部门</th>
						</tr>
                        {% for i in data.object_list %}
                            <tr>

								<td>{{ i.job_name }}</td>
								<td>{{ i.company_name }}</td>
								<td><img src="{% url 'menu_app:getcaptcha' %}?page={{ page }}&position_id={{ position_id }}&flag={{ flag }}&keyword={{ keyword }}&city_id={{ city_id }}&n={{ forloop.counter }}" alt=""></td>
								<td>{{ i.job_req }}</td>
								<td>{{ i.experice_req }}</td>
								<td>{{ i.edu_req }}</td>
								<td>{{ i.company_addr }}</td>
								<td>研发部</td>

							</tr>
                        {% endfor %}
		
					</table>
				</div>
				<div class="ui_tb_h30">
					<div class="ui_flt" style="height: 30px; line-height: 30px;">
						共有
						<span class="ui_txt_bold04">{{ data_count }}</span>
						条记录，当前第
						<span class="ui_txt_bold04">
						{{ page }}/
						{{ page_count }}</span>
						页
					</div>
					<div class="ui_frt">
						<!--    如果是第一页，则只显示下一页、尾页 -->
						
							<a href="{% url 'menu_app:menu_show_data' %}?page=1&position_id={{ position_id }}&flag={{ flag }}&keyword={{ keyword }}&city_id={{ city_id }}"><input type="button" value="首页" class="ui_input_btn01" /></a>
                                {% if data.has_previous %}             {# 是否有上一页 #}

							        <a href="{% url 'menu_app:menu_show_data' %}?page={{ data.previous_page_number }}&position_id={{ position_id }}&flag={{ flag }}&keyword={{ keyword }}&city_id={{ city_id }}"><input type="button" value="上一页" class="ui_input_btn01" /></a>
                                {% endif %}
                                {% if data.has_next %}
							        <a href="{% url 'menu_app:menu_show_data' %}?page={{ data.next_page_number }}&position_id={{ position_id }}&flag={{ flag }}&keyword={{ keyword }}&city_id={{ city_id }}"><input type="button" value="下一页" class="ui_input_btn01" /></a>
                                {% endif %}
							<a href="{% url 'menu_app:menu_show_data' %}?page={{ data.page_count }}&position_id={{ position_id }}&flag={{ flag }}&keyword={{ keyword }}&city_id={{ city_id }}"><input type="button" value="尾页" class="ui_input_btn01" /></a>
							<!--     如果是最后一页，则只显示首页、上一页 -->
						
						转到第<input type="text" id="jumpNumTxt" class="ui_input_txt01" />页
							 <input type="button" class="ui_input_btn01" value="跳转" id='jump' onclick="jump1();" />
					</div>
				</div>
			</div>
		</div>
	</form>
    <script>
        function jump1(){
            page=document.getElementById('jumpNumTxt').value;
            console.log(page);
            location.href="{% url 'menu_app:menu_show_data' %}?page="+page+"&position_id={{ position_id }}&flag={{ flag }}&keyword={{ keyword }}&city_id={{ city_id }}"
        }
    </script>
</body>
{#    反爬虫 之 禁止F12#}
    <script type="text/javascript">

   document.oncontextmenu = new Function("return false;");
   document.onkeydown =document.onkeyup = document.onkeypress=function(){
      if(window.event.keyCode == 123) {
          window.event.cancelBubble = true;
          window.event.returnValue=false;
          return(false);
      }
  }

    </script>

</html>

templates/pie.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <title>饼图</title>
    <!-- 引入 echarts.js -->


</head>
{#<style>#}
{#    body{#}
{#        padding-top: 100px;#}
{#        padding-left: 450px;#}
{#    }#}
{##}
{#</style>#}
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main_pie" style="width: 600px;height:400px;"></div>
    <script src="/static/js/echarts.js"></script>
    <script src="/static/js/jquery-1.7.2.js"></script>
    <script type="text/javascript">

    var charts = echarts.init(document.getElementById('main_pie'));
    charts.showLoading();
// 显示标题，图例和空的坐标轴
        charts.setOption({
            title : {
                text: '招聘猫-各城市发布招聘数量统计',
                subtext: '数据来源大数据统计',
                x:'center'
            },
             tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} ({d}%)"
            },
            legend: {
                orient: 'vertical',
                left: 'left'
            },
                series : [
        {
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]});

        // 异步加载数据
        $.get("{% url 'echarts_app:pie' %}").done(function (data) {
            // 填入数据
            charts.hideLoading();
            charts.setOption({
                series: [{
                    // 根据名字对应到相应的系列
                    name: '数量',
                    data: data
                }]
            })})


    </script>
</body>
</html>

templates/register.html
<!doctype html>
{% load static %}
<html>
<head>
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- font files  -->
<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>
<!-- /font files  -->
<!-- css files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' media="all" />
<!-- /css files -->
</head>
<body>
<h1>Register</h1>
<div class="log">
	<div class="content2">
		<h2>Register</h2>
		<form  action="{% url 'login_regist_app:registlogic'%}" method="post">
            {% csrf_token %}
			<input id="id_username" type="text" name="username" value="USERNAME" onblur="pdusername();" onfocus="if (this.value=='USERNAME' ){this.value = '';}">
            <div><span id="sp_username" ></span></div>
			<input id="id_phone" type="tel" name="phone" value="PHONE" onfocus="if (this.value=='PHONE'){this.value = '';}" onblur="pdpthone();">
            <div>
                <span id="sp_phone"></span></div>
            <input id="id_email" type="email" name="email" value="EMAIL ADDRESS" onfocus="if (this.value=='EMAIL ADDRESS'){this.value = '';}" onblur="pdemail();">
            <div>
                <span id="sp_email"></span></div>
			<input id="id_password" type="password" name="pwd" value="PASSWORD" onfocus="if (this.value=='PASSWORD'){this.value = '';}" onblur="checkpwd()">
            <div>
                <span id="sp_password"></span></div>
			<input type="submit" class="register" value="Register" onclick="return checkstatus();">
		</form>
	</div>
	<div class="clear"></div>
</div>
<div class="footer">
	<p>Copyright &copy;  <a href="http://www.baizhiedu.com/" target="_blank" title="百知教育">百知教育</a></p>
</div>
<script src="{% static 'jq/jquery-1.11.1.js' %}"></script>
<script type="text/javascript">
    function pdusername() {
        username=document.getElementById('id_username');
        if (username.value=='')
        {document.getElementById('id_username').value='USERNAME';}
        $.ajax({
            type:'get',
            url:'{% url 'login_regist_app:usernameajax'%}',
            data:'username='+username.value,
            success:function (meg) {
                sp_username=document.getElementById('sp_username');
                if(meg == "该用户名已注册"){
                   sp_username .innerHTML='该用户名已注册';
                   sp_username.style.color='red'
                }else if (meg == "该用户名可用"){
                    sp_username.innerHTML='该用户名可用';
                    sp_username.style.color='white'
                }
            }
        })
    }
    function pdpthone() {
        phone=document.getElementById('id_phone');
        sp_phone=document.getElementById('sp_phone');
         var reg2=/^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1}))+\d{8})$/;
        if (phone.value=='PHONE'){
            sp_phone.innerHTML='请填写手机号';
            sp_phone.style.color='white'
        }else if(phone.value==''){
            phone.value='PHONE';
            sp_phone.innerHTML='请填写手机号';
            sp_phone.style.color='white'
        }else if(reg2.test(phone.value)){
            sp_phone.innerHTML='手机号可用';
            sp_phone.style.color='white'
        }else {
            sp_phone.innerHTML='手机号格式不正确';
            sp_phone.style.color='white'
        }
    }
    function pdemail() {
        email=document.getElementById('id_email');
        sp_email=document.getElementById('sp_email');
         var reg=/^([a-zA-Z]|[0-9])(\w|\-)+@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;
        if (email.value=='EMAIL ADDRESS'){
            sp_email.innerHTML='请填写邮箱';
            sp_email.style.color='white'
        }else if(email.value==''){
            email.value='EMAIL ADDRESS';
            sp_email.innerHTML='请填写邮箱';
            sp_email.style.color='white'
        }else if(reg.test(email.value)){
            sp_email.innerHTML='邮箱可用';
            sp_email.style.color='white'
        }else {
            sp_email.innerHTML='邮箱格式不正确';
            sp_email.style.color='white'
        }
    }
       function checkpwd() {
        pwd=document.getElementById("id_password");
        s4=document.getElementById("sp_password");
        if (pwd.value=='PASSWORD'){
            s4.innerHTML='请填写密码';
            s4.style.color='white'
        }else if(pwd.value==''){
            pwd.value='PASSWORD';
            s4.innerHTML='请填写密码';
            s4.style.color='white';
        }else if (pwd.value.length<=20&& pwd.value.length>=6) {
            s4.innerHTML="密码可用";
             s4.style.color='white';
        }else {
            s4.innerHTML="密码不合法，请输入6-20位";
             s4.style.color='white';
        }
    }
    function checkstatus() {
        username=document.getElementById("sp_username").innerHTML;
        pwd=document.getElementById("sp_password").innerHTML;
        email=document.getElementById("sp_email").innerHTML;
        phone=document.getElementById("sp_phone").innerHTML;
        if (username=="该用户名可用" && phone=="手机号可用" && email=="邮箱可用" && pwd=="密码可用" ){
            return true
        }else {
            return false
        }
    }
</script>
</body>
</html>

templates/地图1.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    <!-- 引入 echarts.js -->
    <script src="/static/js/jquery-1.7.2.js"></script>
    <script src="/static/js/echarts.js"></script>
	<script src="/static/js/china.js"></script>
</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main_map" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
		// 用户分布图
        // 基于准备好的dom，初始化echarts实例
        var chart = echarts.init(document.getElementById('main_map'));
         $.get("{% url 'echarts_app:map' %}", function (chinaJson) {
          chart.hideLoading();
         chart.setOption({
             title: {
             text: '用户实时分布图',
                    left: 'center',
                    top: 20,
                    textStyle: {
                        color: '#ccc'
                    }
                         },
                tooltip: {},
             series: [{
                 type: 'map',
                 map: 'china',
                 data:chinaJson
             }]
         });
     });


    </script>
</body>
</html>

templates/折线图.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>柱状图</title>
    <!-- 引入 echarts.js -->

</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main666" style="width: 100%;height: 500px"></div>
    <script src="/static/js/jquery-1.7.2.js"></script>
    <script src="/static/js/echarts.js"></script>
    <script type="text/javascript">

        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main666'));
        myChart.showLoading();
        // 指定图表的配置项和数据
        var option = {

    title: {
        text: '简历数量'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:[]
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    toolbox: {
        feature: {
            saveAsImage: {}
        }
    },
    xAxis: {
        axisLabel:{interval: 0},
        type: 'category',
        data: ['北京web','北京爬虫','北京大数据','北京AI', '上海web','上海爬虫','上海大数据','上海AI','广州web','广州爬虫','广州大数据','广州AI','深圳web','深圳爬虫','深圳大数据','深圳AI']
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            name:'职位数量',
            type:'line',
            step: 'start',
            data:[]
        }

    ]
};


        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);



        // 异步加载数据
        $.get("{% url 'echarts_app:zhexianajax' %}").done(function (data) {
            // 填入数据
            myChart.hideLoading();
            myChart.setOption({
                series: [{
                    // 根据名字对应到相应的系列
                    name: '简历数量',
                    data: data
                }]
            });
        });
        // 使用刚指定的配置项和数据显示图表。
    </script>
    <h1></h1>
</body>
</html>

templates/柱状图.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>柱状图</title>
    <!-- 引入 echarts.js -->

</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main_bar" style="width: 600px;height:400px;"></div>
    <script src="/static/js/jquery-1.7.2.js"></script>
    <script src="/static/js/echarts.js"></script>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var echart = echarts.init(document.getElementById('main_bar'));
        echart.showLoading();
// 显示标题，图例和空的坐标轴
        echart.setOption({
            title: {
                text: '四个城市的招聘数量对比'
            },
            tooltip: {},
            legend: {
                data:['']
            },
            xAxis: {
                data: ['北京','上海','广州','深圳']
            },
            yAxis: {},
            series: [{
                name: '数量',
                type: 'bar',
                data: []
            }]
        });

        // 异步加载数据
        $.get("{% url 'echarts_app:barajax' %}").done(function (data) {
            // 填入数据
            echart.hideLoading();
            echart.setOption({
                series: [{
                    // 根据名字对应到相应的系列
                    name: '数量',
                    data: data
                }]
            });
        });
        // 使用刚指定的配置项和数据显示图表。
    </script>
    <h1></h1>
</body>
</html>